# @package _global_

defaults:
  - override /algo: dreamer_v3
  - override /env: gym
  - _self_

wrapper:
  _target_: gymnasium.make
  id: ${env.id}
  render_mode: None
  from_vectors: True
  from_pixels: False

# Experiment
total_steps: 100000
per_rank_batch_size: 16
per_rank_sequence_length: 64
# Checkpoint
checkpoint:
  every: 100000

# Buffer
buffer:
  size: 1000000
  checkpoint: False

# Distribution
distribution:
  type: "auto"

mlp_keys:
  encoder:
    - obs